package catalogue

// Code generated by dev catalogue command DO NOT EDIT

import (
	"github.com/watermint/toolbox/infra/control/app_feature"
)

func AutoDetectedFeatures() []app_feature.OptIn {
	return []app_feature.OptIn{}
}
